### ISSUE TITLE
Problem z utworzeniem Keystore

### ISSUE THREAD

**Issue by J0k3RTwelv3** [Capure/vulcan-api-js#3]
Tworzę projekt z użyciem tego modułu, jednak nie mogę wygenerować Keystore, gdyż request do wygenerowania tokenu Firebase na adres url: [https://android.clients.google.com/c2dm/register3](url) powoduje błąd związany z CORS (nie zwraca Access-Control-Allow-Origin). Ten błąd uniemożliwia korzystanie z API. Co w tym wypadku zrobić?

`Access to XMLHttpRequest at 'https://android.clients.google.com/c2dm/register3' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Capure** [comment]
Biblioteka działa tylko z NodeJS, właśnie ze względu na cors.

**Comment by J0k3RTwelv3** [comment]
Rozumiem, tzn. aplikacja musi być po stronie serwera aby wykonywać te requesty. A poza tym, próbuję użyć getLessons() jednak dostaję cały czas ten błąd bez powodu. Nie dodawałem żadnych opcjonalnych argumentów:
`query["unitId"] = student.unit.id; TypeError: Cannot read properties of undefined (reading 'unit')`

**Comment by Capure** [comment]
Należy najpierw wywołać selectStudent().

**Comment by Capure** [comment]
Po przetestowaniu powodem wydaje się być wspomniany brak wybranego ucznia (taki sam błąd).
Jeśli uczeń został wybrany za pomocą `await client.selectStudent()` i problem dalej występuje, to niestety nie mogę go zreprodukować.
Zamykam issue.
